name: Deploy Node.js app to Tencent Cloud Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: newBranch
        # uses: actions/checkout@v2
        script: |
          git checkout -b release/test
          git push --set-upstream origin release/test
